### ISSUE TITLE
I want to contribute bal folk dates. How? 

### ISSUE THREAD

**Issue by michabal** [qwandor/dancelist-data#99]
I want to update the bal folk events for Marburg/Germany on a regular basis. I have generated the yaml file. How do I push it? 

In gtilab which I know a bit I would commit into a branch, push it and then set up a merge request which will merge if some tests succeed. So I guess it will be similar - but I would need some acces rights?

**Comment by qwandor** [comment]
Hi! Yep, it's pretty similar. I'll add you as a contributor to the project so you can push the branch here directly and create the pull request, but the other usual approach on GitHub is to create a fork under your account and send the PR from there.
